version: '3'
services: 
  redis:
    image: redis:latest
    container_name: redis_cotainer
    expose: 
      - 6379

  python-app:
    image: python:alpine
    container_name: python_app_container
    build: .
    ports: 
      - 3000:3000
    depends_on: 
      - redis