pipeline {
    agent any

    stages {
        stage('Cloning the repo') {
            steps {
                checkout scm
                pwd 
                ls
            }
        }
        
        stage('Run unit testing..') {
            steps {
                sh "python3 '${env.UNIT_TEST_PATH}'"
            }
        }

        stage('Run the containers..') {
            steps {
                sh "docker-compose -f '${env.DOCKER_COMPOSE_PATH}' up -d"
            }
        }

        stage ('Run integration testing..') {
            steps{
                echo "In this stage we should apply the integration testing after running the containers."
            }
        }

        stage('Deployment to Cloud') {
            steps {
                echo 'Here will deploy to AWS.'
            }   
        }
    }
}
