pipeline {
    agent any

    stages {
        stage('Run unit testing') {
            steps {
                sh "python3 '${env.UNIT_TEST_PATH}'"
            }
        }

        stage('Run the containers..') {
            steps {
                sh "docker-compose -f '${env.DOCKER_COMPOSE_PATH}' up -d"
            }
        }

        stage('Deploy') {
            steps {
                echo 'Here will deploy to AWS.'
            }   
        }
    }
}
